### ISSUE TITLE
fatal exception

### ISSUE THREAD

**Issue by alireza2025** [kirill578/Android-Fine-Tuner#1]
i keep getting this error on both emulators and my devices when lunching app and my app crashes.
this is a really handy tool by the way

FATAL EXCEPTION: Thread-3012
                                                                        java.lang.NullPointerException
                                                                            at easazadeh.com.ahd_name.utils.FineTuner$ServerThread.run(FineTuner.java:254)
                                                                            at java.lang.Thread.run(Thread.java:856)

**Comment by kirill578** [comment]
Did you use proguard, or introduced any changes to the code? it does not look like line 254 can throw a `NullPointerException`.  please try copying the latest version.

I assume the issue is that `serverSocket` is null, maybe something blocking it (firewall?) the socket from being created, can you check the logcat for any exceptions?
